# -*- coding: utf-8 -*-
"""Colab_Lec07_data_explore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PjbsJQ7zKsPEpM6Uh0G5ryprVJJuIORL

# Data Exploration with Pandas
<table><tr><td>
<img src="https://resizing.flixster.com/Grjhpv0wcwgi-uhfaC3QM8KFglY=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzdmOWE4MWFiLWVlOWMtNDA4Mi05OTA0LTRiNjMxNTEwMzk1MC5qcGc=" height=300><a href="https://resizing.flixster.com/Grjhpv0wcwgi-uhfaC3QM8KFglY=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzdmOWE4MWFiLWVlOWMtNDA4Mi05OTA0LTRiNjMxNTEwMzk1MC5qcGc=">source</a></td><td><img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRQCHfe9VV3K3Efxv5PYQ_6NYpB20WkKS1zW21UEUmhW1lalECnbwTH3nwQL8XprEMTUCtPeA" height=300><a href="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRQCHfe9VV3K3Efxv5PYQ_6NYpB20WkKS1zW21UEUmhW1lalECnbwTH3nwQL8XprEMTUCtPeA">source</a></td></tr></table>
"""

# importing the package(s) we want to use
import pandas as pd

"""### Let's explore the movies data set more! ###
We'll use the `pd.read_csv()` function to read the csv file into a DataFrame.
"""

csvFile = 'https://raw.githubusercontent.com/csbfx/advpy122-data/master/top_movies_2020.csv'

movies = pd.read_csv(csvFile)
movies.head()

"""### Initial data exploration

We can examine the contents of the resultant DataFrame using the `head()` and `tail()` commands:
"""

### Take a look at the top 3 values of the file
print(movies.head(3))

### How about the last 5 values of a the file?
print(movies.tail)



"""Use the info() method to get a quick description of the dataframe"""

### Get a quick summary of the data using the info() method
movies.info()

"""# Working to filter different elements

Using iloc and loc to extract specific rows and columns
"""

### Get the first 10 elements (movies) of the second column and convert it into a series with a name
ser=movies['Gross'].iloc[:10]
ser

### Get the names of the first 10 movies and convert it into a series and give it type string
ser = movies.loc[:10, ]
ser

### Create a smaller dataframe with last 20 elements and all columns except 'Year'. Give the columns new custom names (your choice).
movies = movies[(movies['Year'] == 1965) | (movies['Gross'] > 10_000_000_000)]
movies

"""Subsetting the dataframe based on conditions"""

### Create a smaller dataframe with movies made in the year 2000s
movies_time=movies[movies.Year<=2000]
movies_time

### How many movies Gross (use 'Gross (Adjusted)') over 1,500,000,000?
movies_gross = movies [(movies['Gross']>150000000)]
movies_gross

"""Customizing the dataframe"""

### Use DataFrame.columns to change the column name to 'Movie','Gross', 'Gross_adj', and 'Year'
movies.columns = ['Movie', 'Gross', 'Gross_adj', 'Year']

### Set the 'Movies' column as the index
movies = movies.set_index(movies.columns[0])
movies

"""Getting some statistic about the data"""

### Get some statistical information about the 'Gross' column
movies['Gross'].min(), movies['Gross'].max()

### What is the average 'Gross (Adjusted)' value for Movies from the 1990s?
mean_gross = movies['Gross'].mean()
print(mean_gross)

### What is the standard deviation of 'Gross (Adjusted)'?
std_gross=movies['Gross'].std()
print(std_gross)